services:
  redis:
    image: redis
    volumes:
      - redis-dump:/data

  app:
    image: node
    depends_on:
      - redis
    volumes: 
      - ./api:/api
      - ./public:/api/public
    working_dir: /api
    command: node app.js --serve-static=true
    ports:
      - 3000:3000
    
  crawler:
    image: node
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on: 
      - redis
    volumes: 
      - ./crawler:/crawler
    working_dir: /crawler
    command: node daemon.js

  dev-server:
    image: node
    depends_on:
      - app
    volumes:
      - ./frontend:/frontend
      - ./public:/frontend/public
    working_dir: /frontend
    command: npx webpack serve --color
    ports:
      - 9000:9000

volumes:
  redis-dump:
