# tail -f /dev/null

services:
  redis:
    image: redis
    volumes:
      - redis-dump:/data

  api:
    image: node
    depends_on:
      - redis
    volumes: 
      - ./api:/api
      - ./public:/api/public
      - ./shared:/api/shared
    working_dir: /api
    command: node api.js --serve-static=true
    ports:
      - 3000:3000
    
  crawler:
    image: node
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on: 
      - redis
    volumes: 
      - ./crawler:/crawler
      - ./shared:/crawler/shared
    working_dir: /crawler
    command: ./daemon.js

  dev-server:
    image: node
    depends_on:
      - api
    volumes:
      - ./frontend:/frontend
      - ./public:/frontend/public
    working_dir: /frontend
    command: npx webpack serve --color
    ports:
      - 8080:8080

volumes:
  redis-dump:
